version: '3.8'  # Use an updated version or omit this line for Docker Compose V2+
services:
  myappdb:
    image: "postgres:latest"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myappdb
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: minisplitwise
    ports:
      - 5432:5432
    networks:
      - my-network
  
  frontend:
    image: pink27/frontend:latest
    ports:
      - "3000:3000"
    networks:
      - my-network
    deploy:
      replicas: 2  # Scale to 2 instances
  
  backend:
    image: pink27/backend:latest
    ports:
      - "8081:8081"
    depends_on:
      - myappdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://myappdb:5432/minisplitwise?createDatabaseIfNotExist=true
    volumes:
      - logs-for-elk:/app/logs
    networks:
      - my-network
    deploy:
      replicas: 2  # Scale to 2 instances

volumes:
  postgres-data:
    driver: local
  logs-for-elk:
    driver: local

networks:
  my-network:
    driver: bridge
