filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/backend_logs/backend.log 

output.logstash:
  hosts: ["logstash:5044"]


processors:
  - dissect:
      tokenizer: "%{timestamp} %{loglevel} %{thread} --- [%{logger}] %{message}"
      field: "message"
      target_prefix: "log"

