---
- name: Pull and run docker image
  hosts: host_machine
  roles:
    - docker
    - docker_compose
    - docker_setup
    - cleanup
  tasks:
    - name: Roll out the Kubernetes deployment
      shell: kubectl rollout restart deployment/striide-frontend
