---
- name: Pull and run docker image
  hosts: host_machine
  # become: yes
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: true

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
      when: docker_version.rc != 0

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: compose_version
      ignore_errors: true

    - name: Install Docker Compose if not present
      apt:
        name: docker-compose
        state: present
      when: compose_version.rc != 0

    - name: Put docker compose file on machine
      copy:
        src: ./docker-compose.yaml
        dest: ~/

    - name: Pull images
      shell: 
        cmd: docker-compose pull
        chdir: ./

    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d --build

    - name: Prune unwanted images
      command: docker image prune --force