# Persistent Volume Claims
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-for-elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Explicitly specify the storage class

---
# Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappdb
  template:
    metadata:
      labels:
        app: myappdb
    spec:
      containers:
        - name: myappdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "myappdb"
            - name: POSTGRES_PASSWORD
              value: "abc123"
            - name: POSTGRES_DB
              value: "minisplitwise"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: myappdb-service
spec:
  selector:
    app: myappdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pink27/frontend:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer


---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pink27/backend:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://myappdb-service:5432/minisplitwise?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "myappdb"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "abc123"
          volumeMounts:
            - name: logs-for-elk
              mountPath: /app/logs
      volumes:
        - name: logs-for-elk
          persistentVolumeClaim:
            claimName: logs-for-elk

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
