apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-for-elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Explicitly specify the storage class