---
- name: Check if Docker is installed
  command: docker --version
  register: docker_version
  ignore_errors: true

- name: Install Docker if not present
  apt:
    name: docker.io
    state: present
  when: docker_version.rc != 0
